import { Inter } from 'next/font/google'
import Header from '../components/header'
import './globals.css'
import ActiveSectionContextProvider from './context/activeSection'
import { Toaster } from 'react-hot-toast'
import Footer from '../components/footer'
import Themeswitch from '../components/themeswitch'
import ThemeContextProvider from './context/themeSwitchContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Vam',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='!scroll-smooth'>
      <body className={`${inter.className} bg-gray-50 text-gray-950 relative pt-28 sm:pt-36
    dark:bg-gray-950 dark:text-gray-50 dark:text-opacity-90`}>
        <div className='bg-[#fbe2e3] -z-10 absolute top-[-6rem] right-[11rem] h-[31.25rem] w-[31.25rem] rounded-full blur-[10rem] 
        sm:w-[68.75rem] dark:bg-[#946263]'></div>
        <div className='bg-[#dbd7fb] -z-10  absolute top-[-1rem] left-[-35rem] h-[31.25rem] w-[50rem] rounded-full blur-[10rem] 
        sm:w-[68.75rem] md:left-[-33rem] lg:left-[-28rem] xl:left-[-15rem] 2xl:left-[-5rem] dark:bg-[#676394]'></div>
        <ThemeContextProvider>
       <ActiveSectionContextProvider>
       <Header />
        {children}
        <Footer />
        <Toaster position='top-right' />
        <Themeswitch /> 
        </ActiveSectionContextProvider> 
        </ThemeContextProvider>
        </body>
    </html>
  )
}
